name: Deploy to Server

on:
  push:
    branches:
      - main  # Деплой при пуше в ветку main
  workflow_dispatch: # Позволяет запускать вручную
    inputs:
      server_ip:
        description: "IP адрес сервера"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка SSH-доступа
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MY_KEY }}
          ssh-passphrase: ${{ secrets.MY_PHRASE }}

      # 3. Копирование файлов на сервер
      - name: Copy files to server
        run: |
          rsync -avz --exclude='.github' ./ ${{ github.event.inputs.server_ip }}:/projects/my-project

      # 4. Запуск Docker Compose на сервере
      - name: Deploy Docker Compose
        run: |
          ssh user@${{ github.event.inputs.server_ip }} << EOF
          cd /path/to/project
          docker-compose down
          docker-compose up -d --build
          EOF
