name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up SSH key and add passphrase
      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Add SSH key with passphrase
        run: |
          expect <<EOF
          spawn ssh-add
          expect "Enter passphrase for"
          send "${{ secrets.MY_PHRASE }}" 
          expect eof
          EOF

      # Set up SSH key for GitHub authentication
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MY_KEY }}

      # Optional: Install dependencies (like Docker)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-backend-image .

      # Test Docker image
      - name: Test Docker image
        run: docker run --rm my-backend-image pytest -s -v

      # Deploy using Docker Compose
      - name: Deploy with Docker Compose
        run: docker compose up -d
