name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: List files in the current directory
        run: ls -la
      
      # Set up SSH key for GitHub authentication
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MY_KEY }}

      # Optional: Install dependencies (like Docker)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build and test
        run: |
          docker build -t my-backend-image .
          docker run --rm my-backend-image pytest -s -v
          
      - name: Deploy to server
        run: |
          scp docker-compose.yml root@45.145.65.204:/root/
          ssh root@45.145.65.204 'cd /root && docker compose up -d'
